import org.junit.Test;

import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'hello' at '3/27/18 9:14 PM' with Gradle 2.10
 *
 * @author hello, @date 3/27/18 9:14 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue(true);
    }
}
